# Generated by Django 2.2.3 on 2019-07-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190707_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='7294a1ac-0d08-48b2-b562-b5cae5209a2f', max_length=36, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
