# Generated by Django 2.2.3 on 2019-07-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190707_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='e08ffff8-16fe-4277-a5f6-fd1179e4b0c0', max_length=36, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
