# Generated by Django 2.2.3 on 2019-07-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190707_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='22cc134b-fc3c-439a-bdf2-5591188dce36', max_length=36, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
