# Generated by Django 2.2.3 on 2019-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190708_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='f959eef9-3ea7-4509-a8fe-159462f5a742', max_length=36, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
