# Generated by Django 2.2.3 on 2019-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190708_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='9aa41222-8206-4503-aad1-d36821becc66', max_length=36, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
