# Generated by Django 2.2.3 on 2019-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190705_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='button_embed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
