# Generated by Django 2.2.3 on 2019-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_button_button_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='button_embed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
