# Generated by Django 2.2.3 on 2019-07-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190714_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquepage',
            name='whatsapp_contactline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='whatsapp_telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
