# Generated by Django 2.2.3 on 2019-07-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20190707_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'ordering': ('date_joined',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
